### PR TITLE
fixed some iOS9 deprecated warnings

### PR DESCRIPTION
**Pull request by NickAger**
The warnings:

NSString+UriCompatibility.m:37:27: warning:
'CFURLCreateStringByAddingPercentEscapes' is deprecated: first
deprecated in iOS 9.0 - Use [NSString
stringByAddingPercentEncodingWithAllowedCharacters:] instead, which
always uses the recommended UTF-8 encoding, and which encodes for a
specific URL component or subcomponent (since each URL component or
subcomponent has different rules for what characters are valid)

NSString+UriCompatibility.m:55:31: warning:
'CFURLCreateStringByReplacingPercentEscapesUsingEncoding' is
deprecated: first deprecated in iOS 9.0 - Use [NSString
stringByRemovingPercentEncoding] or
CFURLCreateStringByReplacingPercentEscapes() instead, which always uses
the recommended UTF-8 encoding.

### CODE REVIEW

**Comment by corinnekrych** [comment]
@NickAger which Xcode do you use to get this warnings? do you get them when opening/building ```DiffMatchPatch.xcodeproj``` ?

**Comment by NickAger** [comment]
I'm using Xcode 7.2 and pulling in DiffMatchPatch as a CocoaPod. However downloading the project directly and compiling using `DiffMatchPatch.xcodeproj` I don't see the warning. To reproduce change the iOS deployment target to 9.0 or greater.

**Comment by corinnekrych** [comment]
@NickAger thanks, indeed.
Testing your branch and running unit tests I have 16 failing tests  :(
I think tests need to be revisited before I can merge. It also reminds me I'll have to add a travis build for this repo.

**Comment by NickAger** [comment]
@corinnekrych apologies I'll investigate why the tests are failing after my changes.

**Comment by corinnekrych** [comment]
closing as he work was done in https://github.com/aerogear/aerogear-diffmatchpatch-ios/pull/6

**Pull request closed without merging**
