### PR TITLE
Arc conversion

### PR DESCRIPTION
**Pull request by NickAger**

### CODE REVIEW

**Comment by corinnekrych** [comment]
@NickAger  Landed!
Thank you for the excellent work :rose:

**Comment by matzew** [comment]
thanks @NickAger :rose:

**Comment by NickAger** [comment]
thanks for the flowers @corinnekrych & @matzew.

**Note**: one change I made that you might want to reverse was removing the version tag from the podspec:

```
s.source       = { :git => 'https://github.com/aerogear/aerogear-diffmatchpatch-ios.git',  :tag => '0.1.2'}
```

I removed `:tag => '0.1.2'` so my pod file would fetch the latest version from my fork. If you want to push an update to the cocoa pods repository  (`pod trunk push DiffMatchPatch.podspec`) you'll need to make a new release e.g. 0.1.3 then re-add the version `:tag => '0.1.3'`

Apologies if this is blindingly obvious to you.

**Comment by corinnekrych** [comment]
Yeap I'll do a release and preprare podspec for it.

**Pull request merged**
